variables:
  DEPLOY_OWNER_PRIVKEY: 0xBF3862CD1EE53F542C483E4F55BEE2D0B13014A7D6AD1B0CA457240C2888C1FB

image: node:10.21.0-buster

cache: &global_cache
  key: ${CI_PROJECT_PATH_SLUG}
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - docker
  script:
    - npm run build
  cache:
    <<: *global_cache

test:
  stage: test
  tags:
    - docker
  script:
    - apt-get update && apt-get install -y netcat
    - npm run test
  cache:
    <<: *global_cache

deploy:
  stage: deploy
  tags:
    - docker
  script:
    - ./node_modules/.bin/ganache-cli -p 8242 -a $DEPLOY_OWNER_PRIVKEY &
      #   - truffle migrate --network integration
  cache:
    <<: *global_cache
